<?php
echo '[
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 22, "Technical Support": "Liu, Laurin", "Status": "Closed"},
{"Product": "Data", "Company": "GRAND INDONESIA", "Warranty": 43, "Technical Support": "Mourani, Maria", "Status": "Assigned"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": "", "Technical Support": "Sellah, Djaouida", "Status": "Closed"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 72, "Technical Support": "St-Denis, Lise", "Status": "Closed"},
{"Product": "Voice", "Company": "Menara BCA", "Warranty": 71, "Technical Support": "Fry, Hedy", "Status": "Closed"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 70, "Technical Support": "Turmel, Nycole", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "Menara BCA", "Warranty": 68, "Technical Support": "Sgro, Judy", "Status": "Assigned"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 67, "Technical Support": "Raynault, Francine", "Status": "Assigned"},
{"Product": "Voice and Data", "Company": "Hotel Indonesia", "Warranty": 66, "Technical Support": "Davidson, Patricia", "Status": "Assigned"},
{"Product": "Data", "Company": "Hotel Indonesia", "Warranty": 65, "Technical Support": "Smith, Joy", "Status": "Assigned"},
{"Product": "Voice", "Company": "Hotel Indonesia", "Warranty": 64, "Technical Support": "Wong, Alice", "Status": "Assigned"},
{"Product": "Data", "Company": "Hotel Indonesia", "Warranty": 63, "Technical Support": "O Neill Gordon, Tilly", "Status": "Assigned"},
{"Product": "Data", "Company": "Hotel Indonesia", "Warranty": 63, "Technical Support": "Ablonczy, Diane", "Status": "Assigned"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 63, "Technical Support": "Duncan, Linda Francis", "Status": "Assigned"},
{"Product": "Voice and Data", "Company": "Menara BCA", "Warranty": 62, "Technical Support": "Bennett, Carolyn", "Status": "Pending"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 61, "Technical Support": "Nash, Peggy", "Status": "Pending"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 61, "Technical Support": "Mathyssen, Irene", "Status": "Pending"},
{"Product": "Voice", "Company": "Banyan Tree", "Warranty": 60, "Technical Support": "Sims, Jinny Jogindera", "Status": "Pending"},
{"Product": "Voice", "Company": "Menara BCA", "Warranty": 60, "Technical Support": "Foote, Judy", "Status": "Closed"},
{"Product": "Voice", "Company": "Banyan Tree", "Warranty": 60, "Technical Support": "Crowder, Jean", "Status": "Closed"},
{"Product": "Voice", "Company": "Banyan Tree", "Warranty": 59, "Technical Support": "Davies, Libby", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 59, "Technical Support": "Yelich, Lynne", "Status": "Closed"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 58, "Technical Support": "Day, Anne-Marie", "Status": "Closed"},
{"Product": "Voice", "Company": "Hotel Indonesia", "Warranty": 58, "Technical Support": "May, Elizabeth", "Status": "Pending"},
{"Product": "Voice", "Company": "Menara BCA", "Warranty": 58, "Technical Support": "Murray, Joyce", "Status": "Resolved"},
{"Product": "Voice", "Company": "PT. PLN", "Warranty": 57, "Technical Support": "Findlay, Kerry-Lynne D.", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 57, "Technical Support": "Brown, Lois", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 57, "Technical Support": "Laverdi\u008fre, H\u008el\u008fne", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 57, "Technical Support": "Boutin-Sweet, Marjolaine", "Status": "Resolved"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 56, "Technical Support": "Crockatt, Joan", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 55, "Technical Support": "Chow, Olivia", "Status": "Resolved"},
{"Product": "Voice", "Company": "PT. PLN", "Warranty": 55, "Technical Support": "McLeod, Cathy", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 55, "Technical Support": "Finley, Diane", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 54, "Technical Support": "LeBlanc, H\u008el\u008fne", "Status": "Resolved"},
{"Product": "Voice", "Company": "PT. PLN", "Warranty": 54, "Technical Support": "Grewal, Nina", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 54, "Technical Support": "Hughes, Carol", "Status": "Resolved"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 53, "Technical Support": "Shea, Gail", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 53, "Technical Support": "Truppe, Susan", "Status": "Resolved"},
{"Product": "Voice", "Company": "PT. PLN", "Warranty": 52, "Technical Support": "Young, Wai", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 52, "Technical Support": "Gallant, Cheryl", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 52, "Technical Support": "Boivin, Fran\u008doise", "Status": "Resolved"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 51, "Technical Support": "Block, Kelly", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 50, "Technical Support": "Ayala, Paulina", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 50, "Technical Support": "Groguh\u008e, Sadia", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 49, "Technical Support": "Charlton, Chris", "Status": "Resolved"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 48, "Technical Support": "Bergen, Candice", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 46, "Technical Support": "Perreault, Manon", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 46, "Technical Support": "James, Roxanne", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 46, "Technical Support": "Ambler, Stella", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "Menara BCA", "Warranty": 46, "Technical Support": "Duncan, Kirsty", "Status": "Resolved"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 45, "Technical Support": "Glover, Shelly", "Status": "Resolved"},
{"Product": "Voice", "Company": "PT. PLN", "Warranty": 45, "Technical Support": "Aglukkaq, Leona", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 44, "Technical Support": "Raitt, Lisa", "Status": "Resolved"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 43, "Technical Support": "Ambrose, Rona", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 42, "Technical Support": "Leitch, Kellie", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 39, "Technical Support": "Leslie, Megan", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 38, "Technical Support": "Hassainia, Sana", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 38, "Technical Support": "Adams, Eve", "Status": "Resolved"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 32, "Technical Support": "Rempel, Michelle", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 32, "Technical Support": "Papillon, Annick", "Status": "Resolved"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 31, "Technical Support": "Sitsabaiesan, Rathika", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 30, "Technical Support": "Quach, Anne Minh-Thu", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 30, "Technical Support": "Ashton, Niki", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 29, "Technical Support": "Moore, Christine", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 28, "Technical Support": "Morin, Isabelle", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 28, "Technical Support": "Blanchette-Lamothe, Lysane", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 28, "Technical Support": "Brosseau, Ruth Ellen", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 28, "Technical Support": "Latendresse, Alexandrine", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 28, "Technical Support": "Dor\u008e Lefebvre, Rosane", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 27, "Technical Support": "Morin, Marie-Claude", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 27, "Technical Support": "Michaud, \u0083laine", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 24, "Technical Support": "P\u008eclet, \u00e9ve", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 23, "Technical Support": "Freeman, Myl\u008fne", "Status": "Resolved"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 22, "Technical Support": "Borg, Charmaine", "Status": "Resolved"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": "", "Technical Support": "Bateman, Joyce", "Status": "Resolved"},
{"Product": "Voice", "Company": "PT. PLN", "Warranty": 43, "Technical Support": "Hiebert, Russ", "Status": "Closed"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 59, "Technical Support": "Jacob, Pierre", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 57, "Technical Support": "Vellacott, Maurice", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 75, "Technical Support": "Boughen, Ray", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 73, "Technical Support": "O Connor, Gordon", "Status": "Closed"},
{"Product": "Data", "Company": "Menara BCA", "Warranty": 72, "Technical Support": "Cotler, Irwin", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 72, "Technical Support": "Oliver, Joe", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 71, "Technical Support": "Tilson, David Allan", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 70, "Technical Support": "Fantino, Julian", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 69, "Technical Support": "Kent, Peter", "Status": "Closed"},
{"Product": "Data", "Company": "GRAND INDONESIA", "Warranty": 69, "Technical Support": "Plamondon, Louis", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 69, "Technical Support": "Schellenberger, Gary", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 68, "Technical Support": "Lauzon, Guy", "Status": "Closed"},
{"Product": "Voice", "Company": "PT. PLN", "Warranty": 68, "Technical Support": "Harris, Richard M.", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 68, "Technical Support": "Goldring, Peter", "Status": "Closed"},
{"Product": "Voice", "Company": "Banyan Tree", "Warranty": 67, "Technical Support": "Atamanenko, Alex", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 67, "Technical Support": "Payne, LaVar", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 67, "Technical Support": "Breitkreuz, Garry W.", "Status": "Closed"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 66, "Technical Support": "Genest, R\u008ejean", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 66, "Technical Support": "MacKenzie, Dave", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 66, "Technical Support": "Hyer, Bruce", "Status": "Closed"},
{"Product": "Data", "Company": "Menara BCA", "Warranty": 66, "Technical Support": "MacAulay, Lawrence", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 65, "Technical Support": "Galipeau, Royal", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 65, "Technical Support": "Marston, Wayne", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 65, "Technical Support": "Hawn, Laurie", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 65, "Technical Support": "Kramp, Daryl", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 65, "Technical Support": "Shipley, Bev", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 65, "Technical Support": "Kerr, Greg", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 65, "Technical Support": "Comartin, Joe", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 64, "Technical Support": "Norlock, Rick", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "Menara BCA", "Warranty": 64, "Technical Support": "McKay, John", "Status": "Closed"},
{"Product": "Voice", "Company": "PT. PLN", "Warranty": 64, "Technical Support": "Mayes, Colin", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "Menara BCA", "Warranty": 64, "Technical Support": "Rae, Bob", "Status": "Closed"},
{"Product": "Voice", "Company": "Banyan Tree", "Warranty": 64, "Technical Support": "Harris, Jack", "Status": "Closed"},
{"Product": "Voice", "Company": "PT. PLN", "Warranty": 64, "Technical Support": "Duncan, John", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 63, "Technical Support": "Chisu, Corneliu", "Status": "Closed"},
{"Product": "Data", "Company": "Menara BCA", "Warranty": 63, "Technical Support": "Garneau, Marc", "Status": "Closed"},
{"Product": "Data", "Company": "Menara BCA", "Warranty": 63, "Technical Support": "Easter, Arnold Wayne", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 63, "Technical Support": "Aspin, Jay", "Status": "Closed"},
{"Product": "Data", "Company": "Menara BCA", "Warranty": 63, "Technical Support": "Goodale, Ralph", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 63, "Technical Support": "Albrecht, Harold", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 63, "Technical Support": "Gravelle, Claude", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 63, "Technical Support": "Komarnicki, Ed", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 62, "Technical Support": "Flaherty, James Michael (Jim)", "Status": "Closed"},
{"Product": "Voice", "Company": "Banyan Tree", "Warranty": 62, "Technical Support": "Rankin, Murray", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "Menara BCA", "Warranty": 62, "Technical Support": "McCallum, John", "Status": "Closed"},
{"Product": "Voice", "Company": "PT. PLN", "Warranty": 62, "Technical Support": "Warawa, Mark", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 62, "Technical Support": "Obhrai, Deepak", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 62, "Technical Support": "Benoit, Leon Earl", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 62, "Technical Support": "Leung, Chungsen", "Status": "Closed"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 61, "Technical Support": "Morin, Marc-Andr\u008e", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 61, "Technical Support": "Sopuck, Robert", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 61, "Technical Support": "Ritz, Gerry", "Status": "Closed"},
{"Product": "Voice", "Company": "Banyan Tree", "Warranty": 61, "Technical Support": "Garrison, Randall", "Status": "Closed"},
{"Product": "Voice", "Company": "PT. PLN", "Warranty": 61, "Technical Support": "Lunney, James", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 61, "Technical Support": "Lukiwski, Tom", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 60, "Technical Support": "Carmichael, John", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 60, "Technical Support": "Menzies, Ted", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 60, "Technical Support": "Valcourt, Bernard", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 60, "Technical Support": "Ashfield, Keith", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 60, "Technical Support": "Nicholson, Rob", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 60, "Technical Support": "Young, Terence H.", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 60, "Technical Support": "Toews, Vic", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 60, "Technical Support": "Sullivan, Mike", "Status": "Closed"},
{"Product": "Data", "Company": "Banyan Tree", "Warranty": 59, "Technical Support": "Patry, Claude", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 59, "Technical Support": "Keddy, Gerald", "Status": "Closed"},
{"Product": "Voice", "Company": "Banyan Tree", "Warranty": 59, "Technical Support": "Bevington, Dennis Fraser", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 59, "Technical Support": "Allen, Malcolm", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "Banyan Tree", "Warranty": 59, "Technical Support": "Rafferty, John", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 59, "Technical Support": "Dreeshen, Earl", "Status": "Closed"},
{"Product": "Voice", "Company": "PT. PLN", "Warranty": 59, "Technical Support": "Kamp, Randy", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 59, "Technical Support": "Merrifield, Rob", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 58, "Technical Support": "Woodworth, Stephen", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 58, "Technical Support": "McColeman, Phil", "Status": "Closed"},
{"Product": "Data", "Company": "PT. PLN", "Warranty": 58, "Technical Support": "Lebel, Denis", "Status": "Closed"},
{"Product": "Voice and Data", "Company": "PT. PLN", "Warranty": 58, "Technical Support": "Lizon, Wladyslaw", "Status": "Closed"}
]';
